FROM node:22.20.0-alpine3.22 AS build
WORKDIR /build
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build
FROM node:22.20.0-alpine3.22 AS release
WORKDIR /app
RUN npm install serve -g
COPY --from=build /build/dist ./dist
EXPOSE 8000
ENTRYPOINT [ "serve", "-s", "dist", "-l", "8000" ]